export const products = [
  {
    categories: "skincare",
    name: "Curology-moist",
    price: "15",
    image: "./src/products/product1.jpg",
  },
  {
    categories: "skincare",
    name: "Ordinary-bd",
    price: "120",
    image: "./src/products/product2.jpg",
  },
  {
    categories: "skincare",
    name: "St-barth",
    price: "25",
    image: "./src/products/product3.jpg",
  },
  {
    categories: "skincare",
    name: "Curology-srm",
    price: "30",
    image: "./src/products/product4.jpg",
  },
  {
    categories: "capsules",
    name: "Intunal-10",
    price: "35",
    image: "./src/products/product5.jpg",
  },
  {
    categories: "capsules",
    name: "Ibuprofen-200",
    price: "40",
    image: "./src/products/product6.jpg",
  },
  {
    categories: "capsules",
    name: "Cetirizine",
    price: "45",
    image: "./src/products/product7.jpg",
  },
  {
    categories: "capsulesTablets",
    name: "Paracetamol",
    price: "45",
    image: "./src/products/product8.jpg",
  },
  {
    categories: "alatBantu",
    name: "Inhaller",
    price: "15",
    image: "./src/products/product9.jpg",
  },
  {
    categories: "skincare",
    name: "GlowFace Cream",
    price: "50",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Radiant Serum",
    price: "60",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Energy Boost Capsule",
    price: "70",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Vitamin C Capsule",
    price: "80",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Hydrating Toner",
    price: "55",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Iron Supplement",
    price: "65",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Zinc Capsule",
    price: "75",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Digital Thermometer",
    price: "25",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Blood Pressure Monitor",
    price: "100",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Soothing Gel",
    price: "35",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Anti-Aging Cream",
    price: "120",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Exfoliating Scrub",
    price: "45",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Omega-3 Capsule",
    price: "95",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Probiotic Supplement",
    price: "110",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Pore Minimizer",
    price: "50",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Pulse Oximeter",
    price: "40",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Collagen Capsule",
    price: "130",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Whitening Lotion",
    price: "75",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Calcium Tablet",
    price: "85",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Hearing Aid",
    price: "200",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Magnesium Capsule",
    price: "55",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Face Mist",
    price: "45",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Sleep Aid Capsule",
    price: "75",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Night Repair Cream",
    price: "85",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Wheelchair",
    price: "350",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Crutches",
    price: "100",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Sunscreen SPF 50",
    price: "70",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Vitamin D Capsule",
    price: "60",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Walking Stick",
    price: "30",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Acne Treatment Gel",
    price: "45",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Vitamin E Oil",
    price: "25",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Hair Growth Capsule",
    price: "100",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Eye Cream",
    price: "55",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Memory Booster Capsule",
    price: "75",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Joint Support Capsule",
    price: "110",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Lip Balm",
    price: "15",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Immune Booster Capsule",
    price: "95",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Knee Brace",
    price: "50",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Body Butter",
    price: "60",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Clay Mask",
    price: "40",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Digestive Support Capsule",
    price: "90",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Electric Massager",
    price: "150",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Hand Cream",
    price: "20",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Toner Spray",
    price: "30",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Body Lotion",
    price: "25",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Antioxidant Capsule",
    price: "120",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Portable Nebulizer",
    price: "250",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Folic Acid Capsule",
    price: "70",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Vitamin B Complex",
    price: "75",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Charcoal Cleanser",
    price: "50",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "CPAP Machine",
    price: "800",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Prenatal Multivitamin",
    price: "85",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Tens Unit",
    price: "180",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Hyaluronic Acid Serum",
    price: "90",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Keto Support Capsule",
    price: "125",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Hair Loss Prevention Capsule",
    price: "100",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Orthopedic Pillow",
    price: "60",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Eye Health Capsule",
    price: "80",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Facial Oil",
    price: "70",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Detox Capsule",
    price: "115",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Sleep Better Capsule",
    price: "95",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Adjustable Bed",
    price: "1500",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Energy Release Capsule",
    price: "135",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Focus Enhancer Capsule",
    price: "125",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Whitening Facial Mask",
    price: "45",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Standing Frame",
    price: "950",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Hand Sanitizer",
    price: "15",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Mood Stabilizer Capsule",
    price: "90",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Shower Chair",
    price: "180",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Body Oil",
    price: "45",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Moisturizing Mask",
    price: "55",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Brain Booster Capsule",
    price: "145",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Lift Chair",
    price: "1200",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Anti-Stress Capsule",
    price: "105",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Skin Brightener",
    price: "35",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Memory Enhancer Capsule",
    price: "135",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Electric Wheelchair",
    price: "2200",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Acne Prevention Cream",
    price: "75",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Healthy Heart Capsule",
    price: "125",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Anti-Aging Capsule",
    price: "115",
    image: "./src/products/product.png",
  },
  {
    categories: "alatBantu",
    name: "Transfer Board",
    price: "250",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Protein Supplement",
    price: "135",
    image: "./src/products/product.png",
  },
  {
    categories: "skincare",
    name: "Hydrating Cleanser",
    price: "45",
    image: "./src/products/product.png",
  },
  {
    categories: "capsules",
    name: "Energy Booster Capsule",
    price: "85",
    image: "./src/products/product.png",
  },
];
